#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
web: java ${symbol_dollar}JAVA_OPTS -jar ${artifactId}-web/target/dependency/webapp-runner.jar --port ${symbol_dollar}PORT ${artifactId}-web/target/*.war
